import type { CSSProperties } from 'react';
import source from './source.json';
import { motion, useReducedMotion } from 'framer-motion';
import { DataPulse, FloatingElement, HeroLayer, HeroConcept, HeroDigital, keynoteEase } from './motion';
import { SharedLifecycle } from './SharedLifecycle';
import { asset, Copilot, Flow, Heading, Reveal, Takeaway } from './primitives';
export const titles=source.map((s,i)=>i===0?'GitHub Copilot: od nápadu k deploymentu':i===2?s.texts.slice(0,2).join(' '):s.texts[0]);
function Orbit({partner=false}:{partner?:boolean}){
 const nodes=source[partner?4:3].texts.slice(1,10);
 return <div className={`orbit ${partner?'partner-orbit':''}`}><DataPulse className="orbit-stream" path="M 5 50 A 45 45 0 1 1 95 50 A 45 45 0 1 1 5 50" viewBox="0 0 100 100" period={12}/><div className="orbit-ring"/><div className="orbit-ring inner"/><div className="orbit-core">{partner?<><svg className="person-symbol" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" aria-hidden="true"><circle cx="24" cy="14" r="8"/><path d="M9 42v-5a15 15 0 0 1 30 0v5Z"/></svg><strong>Partner</strong></>:<><Copilot/><strong>GitHub Copilot</strong></>}</div>{nodes.map((n,i)=>{const angle=(i*360/9-90)*Math.PI/180;return <div key={n} className="orbit-label" style={{left:`${50+43*Math.cos(angle)}%`,top:`${50+43*Math.sin(angle)}%`,'--delay':`${i*.07}s`} as CSSProperties}><span className="orbit-dot"/>{partner?<FloatingElement period={7+i*.43} delay={-i*.61}>{n}</FloatingElement>:n}</div>})}</div>
}
function Extension(){const names=['Instructions','Agents','Skills','MCP & Tools']; const descriptions=['Jak má pracovat','Na co se má specializovat','Co má umět','S čím může pracovat'];return <div className="extensions">{names.map((n,i)=><Reveal key={n} delay={i*.15} className={`extension extension-${i}`}><div className="extension-symbol" aria-hidden="true">{['≡','◎','▤','↗'][i]}</div><span className="step-no">0{i+1}</span><h2>{n}</h2><p>{descriptions[i]}</p></Reveal>)}</div>}
export function Scene({index,fullscreen}:{index:number;fullscreen:()=>void}){
 const t=source[index].texts; const reduced=useReducedMotion();
 switch(index){
 case 0:return <div className="hero"><div className="hero-copy"><Reveal><p className="eyebrow">PARTNER WEBINAR</p><h1><span>GitHub Copilot:</span><br/>od nápadu<br/><em>k deploymentu</em></h1></Reveal><Reveal delay={.15}><p className="hero-subtitle">Jak proměnit zákaznický nápad<br/>ve fungující řešení</p><p className="hero-audience">Pro Microsoft partnery · SMB segment</p></Reveal><Reveal delay={.3}><button className="start" onClick={fullscreen}>Spustit prezentaci <span>↗</span></button><p className="key-hint">← → snímky <span>·</span> F celá obrazovka</p></Reveal></div><div className="hero-art" aria-hidden="true"><HeroDigital/><HeroLayer className="art-cloud" src={asset('hero-cloud.webp')} delay={.15} period={8.8}/><HeroLayer className="art-code" src={asset('hero-code.webp')} delay={.5} period={10}/><HeroLayer className="art-data" src={asset('hero-data.webp')} delay={.85} period={7.3}/><DataPulse className="hero-stream" path="M 5 75 C 5 20 35 10 55 15 S 95 35 95 62 S 63 92 45 84" viewBox="0 0 100 100" period={6} delay={1.6} track/><motion.div className="art-copilot" initial={reduced?false:{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{delay:reduced?0:1.2,duration:reduced?0:.65,ease:keynoteEase}}><Copilot/></motion.div><HeroConcept/></div></div>;
 case 1:case 2:return <div className="question"><span className="question-mark" aria-hidden="true">?</span><Reveal><h1>{index===1?<>Jak dnes<br/>používáte <em>AI?</em></>:<>Co už dnes necháváte<br/><em>AI dělat za vás?</em></>}</h1></Reveal><div className="question-line"/></div>;
 case 3:case 4:return <><Heading>{t[0]}</Heading><Orbit partner={index===4}/><Takeaway>{index===3?t[10]:t[10]}</Takeaway></>;
 case 5:return <><Heading>{t[0]}</Heading><div className="environment"><Reveal className="workspace"><div className="workspace-heading"><img src={asset('vscode.png')} alt="VS Code"/><div><p className="eyebrow">HLAVNÍ PRACOVNÍ PROSTOR</p><h2>IDE / VS Code</h2><p>chat, plan, agent mode</p></div></div><img className="ide-screenshot" src={asset('vscode.webp')} alt="Původní screenshot prostředí VS Code s Copilot chatem"/></Reveal><div className="satellites">{[['CLI','Terminál a skripty'],['GitHub','Pull requesty, issues, code review'],['Cloud / Agents','Delegované úlohy na pozadí']].map(([a,b],i)=><Reveal key={a} delay={.2+i*.15}><span className="satellite-line"><DataPulse period={7.8} delay={1+i*1.8}/></span><h3>{a}</h3><p>{b}</p></Reveal>)}</div></div></>;
 case 6:return <><Heading>{t[0]}</Heading><div className="model-layout"><Reveal className="model-image"><div className="copilot-title"><Copilot/><h2>GitHub Copilot</h2></div><p>Jedno prostředí</p><img src={asset('models.png')} alt="Výběr modelu v Copilot chatu, screenshot ze zdrojové prezentace"/><p className="image-caption">Výběr modelu přímo v Copilot chatu</p></Reveal><div className="model-factors">{[['RYCHLOST','Jak rychle odpovídá'],['SCHOPNOSTI','Jak složité úlohy zvládne'],['CENA','Kolik AI Credits spotřebuje']].map(([a,b],i)=><Reveal key={a} delay={i*.15} className={`model-factor factor-${i}`}><span className="step-no">0{i+1}</span><h3>{a}</h3><p>{b}</p></Reveal>)}</div></div><Takeaway>{t[9]}</Takeaway></>;
 case 7:return <><Heading>GitHub Copilot už není<br/>jen <em>autocomplete</em></Heading><div className="evolution"><Flow items={['Doplň','Vysvětli','Navrhni','Naplánuj','Proveď','Deleguj']} pulse period={7}/><div className="flow-endpoints"><span>JEDNOTLIVÉ ŘÁDKY KÓDU</span><span>CELÉ ÚLOHY A DELEGOVÁNÍ</span></div></div><Takeaway>{t[t.length-1]}</Takeaway></>;
 case 8:return <><Heading>{t[0]}</Heading><Extension/></>;
 case 9:return <><Heading>{t[0]}</Heading><div className="brain-system"><div className="brain-beam" aria-hidden="true"><DataPulse period={9} pingPong/></div>{[['MODEL','Mozek','Umí přemýšlet'],['CONTEXT / SKILLS','Znalosti','Dávají mu znalosti'],['TOOLS / MCP','Ruce','Umožní něco skutečně udělat']].map(([a,b,c],i)=><Reveal key={a} delay={i*.25} className="system-part"><div className={`system-core system-${i}`}><span>{['◎','≡','↗'][i]}</span></div><p className="eyebrow">{a}</p><h2>{b}</h2><p>{c}</p></Reveal>)}</div><Takeaway>Samotný model umí přemýšlet. Kontext mu dává znalosti. Nástroje mu umožní něco skutečně udělat.</Takeaway></>;
 case 10:return <><Heading>{t[0]}</Heading><div className="azure-connection"><DataPulse className="azure-journey" pingPong period={12}/><Reveal><Copilot/><h2>GitHub Copilot</h2></Reveal><div className="connection-track"/><Reveal delay={.2} className="azure-skills"><span className="eyebrow">PROPOJENÍ</span><h3>Azure Skills</h3></Reveal><div className="connection-track"/><Reveal delay={.4}><div className="azure-word">Azure</div></Reveal></div><Flow items={['Zjisti','Navrhni','Připrav','Nasaď']} className="azure-flow"/><Takeaway>{t[t.length-1]}</Takeaway></>;
 case 11:return <><Heading>{t[0]}</Heading><div className="partner-roles">{[1,3,5].map((n,i)=><Reveal className="role-row" key={n} delay={i*.18}><span className="step-no">0{i+1}</span><h2>{t[n]}</h2><span className="role-arrow">→</span><p>{t[n+1].replace(/^→\s*/,'')}</p></Reveal>)}</div><Takeaway>{t[7]}</Takeaway></>;
 case 12:case 13:return <><Heading><motion.span key={index} initial={reduced?false:{opacity:.2}} animate={{opacity:1}} transition={{duration:reduced?0:.45}}>{t[0]}</motion.span></Heading><SharedLifecycle production={index===13}/>{index===12?<Reveal key="poc-question" delay={.6} className="poc-question"><h2>{t[11]}</h2><p>{t[12]}</p></Reveal>:<Reveal key="production-details" className="production-areas" delay={.55}><p className="eyebrow">OBLASTI PRODUKČNÍ PŘÍPRAVY</p><div>{t.slice(12,19).map((x,i)=><motion.span key={x} initial={reduced?false:{opacity:0,y:6}} animate={{opacity:1,y:0}} transition={{delay:reduced?0:.6+i*.07,duration:.4,ease:keynoteEase}}>{x}</motion.span>)}</div></Reveal>}{index===13&&<Takeaway>{t[19]}</Takeaway>}</>;
 case 14:return <><Heading>Kvalitní výsledek začíná<br/><em>kvalitním zadáním</em></Heading><div className="input-comparison"><Reveal className="ambiguous"><h2>„Vytvoř mi aplikaci.“</h2><div className="branch-lines" aria-hidden="true"><i/><i/><i/></div><div className="outcomes"><span>Webová aplikace?</span><span>Mobilní aplikace?</span><span>Interní nástroj?</span></div></Reveal><Reveal delay={.25} className="clear-input"><h2>„Takhle má aplikace fungovat.“</h2><div className="converge-line" aria-hidden="true"/><strong>Jasný výsledek</strong></Reveal></div><Takeaway>{t[7]}</Takeaway></>;
 case 15:return <><Heading>{t[0]}</Heading><div className="documentation">{['Rozhovor','Dokumentace','Plán'].map((x,i)=><Reveal key={x} delay={i*.18} className={`doc-step doc-${i}`}><span className="step-no">0{i+1}</span><h2>{x}</h2>{i===0?<><div className="conversation-lines" aria-hidden="true"><i/><i/><i/></div><p>Nestrukturované povídání o problému se zákazníkem</p></>:i===1?<ul>{t.slice(9).map(x=><li key={x}>{x}</li>)}</ul>:<><div className="plan-lines" aria-hidden="true"><i/><i/><i/></div><p>Copilot připraví kroky a realizuje změny</p></>}</Reveal>)}</div></>;
 case 16:return <><Heading>AI pracuje.<br/><em>Člověk rozhoduje.</em></Heading><div className="human-steps">{[['Plánuj','Než AI začne pracovat'],['Kontroluj','Každou změnu a každý krok'],['Testuj','Výsledek, ne dojem'],['Schvaluj','Nasazení je vaše rozhodnutí']].map(([a,b],i)=><Reveal key={a} delay={i*.15}><span className="step-no">0{i+1}</span><h2>{a}</h2><p>{b}</p></Reveal>)}</div><Takeaway><strong>Důvěřuj, ale ověřuj.</strong> AI rozšiřuje naši kapacitu, ale odpovědnost za výsledek zůstává na člověku.</Takeaway></>;
 case 17:return <><Heading>{t[0]}</Heading><div className="pricing"><Reveal className="price-business"><p className="eyebrow">GitHub Copilot</p><h2>Business</h2><div className="price">$19 <span>za uživatele / měsíc<small>list price USD</small></span></div><ul><li><strong>1 900 AI Credits</strong> měsíčně na uživatele</li><li>Centrální správa a policy management</li><li>Sdílený pool kreditů v organizaci</li></ul></Reveal><Reveal delay={.2} className="price-enterprise"><p className="eyebrow">Copilot</p><h2>Enterprise</h2><div className="price">$39 <span>za uživatele / měsíc<small>list price USD</small></span></div><ul><li><strong>3 900 AI Credits</strong> měsíčně</li><li>Early access k novým modelům a funkcím</li></ul></Reveal></div></>;
 case 18:return <><Heading>{t[0]}</Heading><Reveal className="credits-equation"><span>Model</span><b>×</b><span>rozsah úlohy</span><b>=</b><strong>AI spotřeba</strong></Reveal><p className="credits-context">kontext · délka interakce · výstup · agentní kroky</p><div className="credits-levels">{[['$','Lightweight model','Rychlé a jednoduché úlohy'],['$$','Standardní model','Běžná každodenní práce'],['$$$','Dlouhá agentní session / výkonný model','Komplexní problémy a delegované úlohy']].map(([a,b,c],i)=><Reveal key={a} delay={i*.14}><div className="credit-value">{a}</div><h3>{b}</h3><p>{c}</p></Reveal>)}</div><Takeaway><strong>Optimalizujte model podle úlohy.</strong> Ne každá úloha potřebuje nejsilnější model. Výběr modelu ovlivňuje rychlost i náklady.</Takeaway></>;
 case 19:return <><Heading>{t[0]}</Heading><div className="business-origin"><Copilot/><div><h2>GitHub Copilot</h2><p>Širší schopnost partnera</p></div></div><Flow items={['Rychlejší PoC','Validovaná opportunity','Projekt v Azure','Azure consumption + partnerské služby']} className="business-flow" pulse period={8.5}/><div className="business-result"><p>Pro partnera není GitHub Copilot jen další seat licence.</p><h2>Hodnota vzniká v tom,<br/><em>co partner dokáže dodat.</em></h2></div><Takeaway>Adopce, AI a Azure consumption, governance a implementační služby.</Takeaway></>;
 default:return <div className="closing"><Reveal><p className="eyebrow">OTÁZKY A DISKUZE</p><h1>Děkujeme<br/><em>za pozornost.</em></h1><div className="closing-line"/><p>Juraj Kurtulik</p><p className="closing-role">Solutions Architect · CoE Microsoft, TD SYNNEX</p></Reveal></div>;
 }
}
